# Generated by Django 5.1.1 on 2024-09-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='обязательное поле', max_length=254, verbose_name='email')),
                ('full_name', models.CharField(help_text='обязательное поле', max_length=200, verbose_name='Ф.И.О.')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент сервиса',
                'verbose_name_plural': 'клиенты сервиса',
                'ordering': ('full_name',),
            },
        ),
    ]
