# Generated by Django 5.1.1 on 2024-09-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_rename_serviceclient_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_topic', models.CharField(max_length=100, verbose_name='тема')),
                ('msg_body', models.TextField(verbose_name='содержимое')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения для рассылок',
                'ordering': ('msg_topic',),
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('full_name',), 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Ф.И.О.'),
        ),
    ]
